name: Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types:
      - published

jobs:
  windows-build:
    runs-on: windows-2019

    strategy:
      fail-fast: false
      matrix:
        config:
          - preset: msvc-release
          - preset: msvc-debug

    env:
      CXX: cl.exe
      CC: cl.exe
      BUILDCACHE_COMPRESS: true
      BUILDCACHE_DIRECT_MODE: true
      BUILDCACHE_ACCURACY: SLOPPY
      BUILDCACHE_DIR: ${{ github.workspace }}/.buildcache
      BUILDCACHE_LUA_PATH: ${{ github.workspace }}/tools

    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-ninja@master
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      # ==== BUILD ====
      - name: Build
        run: |
          $devShell = &"${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -find **\Microsoft.VisualStudio.DevShell.dll
          $installPath = &"${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationpath
          Import-Module $devShell
          Enter-VsDevShell -VsInstallPath $installPath -SkipAutomaticLocation -DevCmdArguments "-arch=amd64 -vcvars_ver=14.29"
          cmake --preset=${{ matrix.config.preset }}
          cmake --build build\${{ matrix.config.preset }} --target soro-test

      # ==== TESTS ====
      - name: Run Tests
        run: .\build\${{ matrix.config.preset }}\soro-test.exe